In [ ]:
# The aim is to determine the type of Eryhemato-Squamous Disease.

In [1]:
# importing required libraried
import pandas as pd
import numpy as np
from pandas.plotting import scatter_matrix
import matplotlib.pyplot as plt

In [23]:
from sklearn import model_selection
from sklearn.metrics import classification_report
from sklearn.metrics import confusion_matrix
from sklearn.metrics import accuracy_score


In [24]:
# importing sklearn classification models

from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn.naive_bayes import GaussianNB
from sklearn.svm import SVC

from sklearn.discriminant_analysis import LinearDiscriminantAnalysis

In [5]:
# renaming columns
names = ["erythema" , "scaling", "definite_borders", "itching", "koebner_phenomenon", "polygonal_papules", "follicular_papules", "oral_mucosal_involvement", "knee and elbow involvement", "scalp_involvement", "family_history",
"melanin_incontinence","eosinophils_in_the_infiltrate", "PNL_infiltrate", "fibrosis_of_the_papillary_dermis", "exocytosis", "acanthosis", "hyperkeratosis", "parakeratosis", "clubbing_of_the_rete_ridges", "elongation_of_the_rete_ridges", "thinning_of_the_suprapapillary_epidermis", "spongiform_pustule", "munro_microabcess", "focal_hypergranulosis", "disappearance_of_the_granular_layer", "vacuolisation_and_damage_of_basal_layer", "spongiosis", "saw-tooth_appearance_of_retes", "follicular_horn_plug", "perifollicular_parakeratosis", "inflammatory_monoluclear_inflitrate", "band-like_infiltrate", "Age", "Disease"]

In [12]:
# Loading dermatology dataset, download from UCI
dataset = pd.read_csv('dermatology3.csv')

In [2]:
#dataset.dtypes

In [5]:
dataset['Age'].dtypes

dtype('O')

In [6]:
dataset.isin(["?"]).sum(axis=0)

erythema                                    0
scaling                                     0
definite_borders                            0
itching                                     0
koebner_phenomenon                          0
polygonal_papules                           0
follicular_papules                          0
oral_mucosal_involvement                    0
knee and elbow involvement                  0
scalp_involvement                           0
family_history                              0
melanin_incontinence                        0
eosinophils_in_the_infiltrate               0
PNL_infiltrate                              0
fibrosis_of_the_papillary_dermis            0
exocytosis                                  0
acanthosis                                  0
hyperkeratosis                              0
parakeratosis                               0
clubbing_of_the_rete_ridges                 0
elongation_of_the_rete_ridges               0
thinning_of_the_suprapapillary_epi

In [7]:
#  class distrubution of the target column
#dataset.groupby('Disease').size()

In [1]:
#dataset.corr()

In [13]:
dataset['Age'].isin(["?"]).sum(axis=0)

8

In [61]:
import numpy as np

In [115]:
dataset.isna().sum()

erythema                                      0
scaling                                       0
definite_borders                              0
itching                                       0
koebner_phenomenon                            0
polygonal_papules                             0
follicular_papules                            0
oral_mucosal_involvement                      0
knee and elbow involvement                    0
scalp_involvement                             0
family_history                                0
melanin_incontinence                          0
eosinophils_in_the_infiltrate                 0
PNL_infiltrate                                0
fibrosis_of_the_papillary_dermis              0
exocytosis                                    0
acanthosis                                    0
hyperkeratosis                                0
parakeratosis                                 0
clubbing_of_the_rete_ridges                   0
elongation_of_the_rete_ridges           

In [14]:
# code will replace the special character to nan and then drop the columns 
dataset['Age'] = dataset['Age'].replace('?',np.nan)

In [15]:
dataset['Age'].isna().sum()

8

In [18]:
dataset.isna().any()

erythema                                    False
scaling                                     False
definite_borders                            False
itching                                     False
koebner_phenomenon                          False
polygonal_papules                           False
follicular_papules                          False
oral_mucosal_involvement                    False
knee and elbow involvement                  False
scalp_involvement                           False
family_history                              False
melanin_incontinence                        False
eosinophils_in_the_infiltrate               False
PNL_infiltrate                              False
fibrosis_of_the_papillary_dermis            False
exocytosis                                  False
acanthosis                                  False
hyperkeratosis                              False
parakeratosis                               False
clubbing_of_the_rete_ridges                 False


In [43]:
dataset.isna().sum()

erythema                                    0
scaling                                     0
definite_borders                            0
itching                                     0
koebner_phenomenon                          0
polygonal_papules                           0
follicular_papules                          0
oral_mucosal_involvement                    0
knee and elbow involvement                  0
scalp_involvement                           0
family_history                              0
melanin_incontinence                        0
eosinophils_in_the_infiltrate               0
PNL_infiltrate                              0
fibrosis_of_the_papillary_dermis            0
exocytosis                                  0
acanthosis                                  0
hyperkeratosis                              0
parakeratosis                               0
clubbing_of_the_rete_ridges                 0
elongation_of_the_rete_ridges               0
thinning_of_the_suprapapillary_epi

In [19]:
#dataset["Age"].fillna( method ='ffill', inplace = True)
dataset['Age']=dataset['Age'].fillna(dataset['Age'].median())

In [21]:
dataset['Age'].isna().sum()

0

In [22]:
dataset.isna().sum()

erythema                                    0
scaling                                     0
definite_borders                            0
itching                                     0
koebner_phenomenon                          0
polygonal_papules                           0
follicular_papules                          0
oral_mucosal_involvement                    0
knee and elbow involvement                  0
scalp_involvement                           0
family_history                              0
melanin_incontinence                        0
eosinophils_in_the_infiltrate               0
PNL_infiltrate                              0
fibrosis_of_the_papillary_dermis            0
exocytosis                                  0
acanthosis                                  0
hyperkeratosis                              0
parakeratosis                               0
clubbing_of_the_rete_ridges                 0
elongation_of_the_rete_ridges               0
thinning_of_the_suprapapillary_epi

In [49]:
dataset.isna().sum()

erythema                                    0
scaling                                     0
definite_borders                            0
itching                                     0
koebner_phenomenon                          0
polygonal_papules                           0
follicular_papules                          0
oral_mucosal_involvement                    0
knee and elbow involvement                  0
scalp_involvement                           0
family_history                              0
melanin_incontinence                        0
eosinophils_in_the_infiltrate               0
PNL_infiltrate                              0
fibrosis_of_the_papillary_dermis            0
exocytosis                                  0
acanthosis                                  0
hyperkeratosis                              0
parakeratosis                               0
clubbing_of_the_rete_ridges                 0
elongation_of_the_rete_ridges               0
thinning_of_the_suprapapillary_epi

In [107]:
dataset.isna().any()

erythema                                    False
scaling                                     False
definite_borders                            False
itching                                     False
koebner_phenomenon                          False
polygonal_papules                           False
follicular_papules                          False
oral_mucosal_involvement                    False
knee and elbow involvement                  False
scalp_involvement                           False
family_history                              False
melanin_incontinence                        False
eosinophils_in_the_infiltrate               False
PNL_infiltrate                              False
fibrosis_of_the_papillary_dermis            False
exocytosis                                  False
acanthosis                                  False
hyperkeratosis                              False
parakeratosis                               False
clubbing_of_the_rete_ridges                 False


In [27]:
dataset['Age'].dtypes

dtype('O')

In [28]:
dataset['Age'] = dataset['Age'].astype(np.int64)

In [29]:
dataset['Age'].dtypes

dtype('int64')

In [30]:
dataset.to_csv('dermatology3.csv', index=False)

In [31]:
df = pd.read_csv('dermatology3.csv')
df.dtypes

erythema                                    int64
scaling                                     int64
definite_borders                            int64
itching                                     int64
koebner_phenomenon                          int64
polygonal_papules                           int64
follicular_papules                          int64
oral_mucosal_involvement                    int64
knee and elbow involvement                  int64
scalp_involvement                           int64
family_history                              int64
melanin_incontinence                        int64
eosinophils_in_the_infiltrate               int64
PNL_infiltrate                              int64
fibrosis_of_the_papillary_dermis            int64
exocytosis                                  int64
acanthosis                                  int64
hyperkeratosis                              int64
parakeratosis                               int64
clubbing_of_the_rete_ridges                 int64


In [87]:
dataset['Disease'] = dataset['Disease'].astype(np.int64)

In [88]:
dataset.dtypes

erythema                                     int64
scaling                                      int64
definite_borders                             int64
itching                                      int64
koebner_phenomenon                           int64
polygonal_papules                            int64
follicular_papules                           int64
oral_mucosal_involvement                     int64
knee and elbow involvement                   int64
scalp_involvement                            int64
family_history                               int64
melanin_incontinence                         int64
eosinophils_in_the_infiltrate                int64
PNL_infiltrate                               int64
fibrosis_of_the_papillary_dermis             int64
exocytosis                                   int64
acanthosis                                   int64
hyperkeratosis                               int64
parakeratosis                                int64
clubbing_of_the_rete_ridges    

In [36]:
# split dataset into train , test and validation sets

array = dataset.values
X = array[:, 0:-1] # all rows taken, all columns except last one
Y = array[:, -1] # all rows takne, only last column taken
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(X,Y,test_size=0.2, random_state=7)
##############################
from sklearn.preprocessing import StandardScaler
sc=StandardScaler()
sc.fit(x_train)
x_train_sc=sc.transform(x_train)
x_test_sc=sc.transform(x_test)
#print(x_train[:5])
#print(x_train_sc[:5])
################################
from sklearn.neighbors import KNeighborsClassifier
clf=KNeighborsClassifier(n_neighbors=5)
clf.fit(x_train_sc,y_train)
y_pred=clf.predict(x_test_sc)
print(y_pred)
# Y = array
#X_train, X_test, Y_train, Y_test = model_selection.train_test_split(X, Y, test_size=0.2, random_state=7) # 20 percent test dataset

[6 3 5 1 1 3 4 1 3 5 4 4 2 5 1 5 4 4 1 1 2 6 2 5 4 2 3 1 3 1 2 1 3 1 2 1 3
 3 2 1 3 1 3 2 4 5 3 5 4 1 3 1 5 2 4 1 2 5 4 2 4 1 4 4 1 2 1 1 2 1 5 4 3]


In [39]:
from sklearn.metrics import confusion_matrix,classification_report,accuracy_score
print(confusion_matrix(y_test,y_pred))
print(classification_report(y_test,y_pred))
print('Accuracy score %.2f'%accuracy_score(y_test,y_pred))

[[21  0  0  0  0  0]
 [ 0 12  0  3  0  0]
 [ 0  0 13  0  0  0]
 [ 0  1  0 11  0  0]
 [ 0  0  0  0 10  0]
 [ 0  0  0  0  0  2]]
              precision    recall  f1-score   support

           1       1.00      1.00      1.00        21
           2       0.92      0.80      0.86        15
           3       1.00      1.00      1.00        13
           4       0.79      0.92      0.85        12
           5       1.00      1.00      1.00        10
           6       1.00      1.00      1.00         2

    accuracy                           0.95        73
   macro avg       0.95      0.95      0.95        73
weighted avg       0.95      0.95      0.95        73

Accuracy score 0.95


In [40]:
from sklearn.svm import  SVC
svm=SVC(kernel='linear',C=1,random_state=0)
svm.fit(x_train_sc,y_train)
y_pred=svm.predict(x_test_sc)
print(y_pred)

[6 3 5 1 1 3 2 1 3 5 4 4 2 5 1 5 4 2 1 1 2 6 2 5 4 2 3 1 3 1 4 1 3 1 2 1 3
 3 2 1 3 1 3 2 4 5 3 5 4 1 3 1 5 2 4 1 2 5 4 2 4 1 4 4 1 2 1 1 2 1 5 4 3]


In [41]:
print('misclassified samples:%d'%(y_test!=y_pred).sum())


misclassified samples:1


In [42]:
print(confusion_matrix(y_test,y_pred))
print(classification_report(y_test,y_pred))
print('Accuracy:%.2f'%accuracy_score(y_test,y_pred))

[[21  0  0  0  0  0]
 [ 0 14  0  1  0  0]
 [ 0  0 13  0  0  0]
 [ 0  0  0 12  0  0]
 [ 0  0  0  0 10  0]
 [ 0  0  0  0  0  2]]
              precision    recall  f1-score   support

           1       1.00      1.00      1.00        21
           2       1.00      0.93      0.97        15
           3       1.00      1.00      1.00        13
           4       0.92      1.00      0.96        12
           5       1.00      1.00      1.00        10
           6       1.00      1.00      1.00         2

    accuracy                           0.99        73
   macro avg       0.99      0.99      0.99        73
weighted avg       0.99      0.99      0.99        73

Accuracy:0.99


In [44]:
from sklearn.tree import DecisionTreeClassifier

dtc = DecisionTreeClassifier(random_state=1)
dtc.fit(x_train_sc,y_train)
dtc.score(x_test_sc,y_test)
print(confusion_matrix(y_test,y_pred))
print(classification_report(y_test,y_pred))
print('Accuracy:%.2f'%accuracy_score(y_test,y_pred))

[[21  0  0  0  0  0]
 [ 0 14  0  1  0  0]
 [ 0  0 13  0  0  0]
 [ 0  0  0 12  0  0]
 [ 0  0  0  0 10  0]
 [ 0  0  0  0  0  2]]
              precision    recall  f1-score   support

           1       1.00      1.00      1.00        21
           2       1.00      0.93      0.97        15
           3       1.00      1.00      1.00        13
           4       0.92      1.00      0.96        12
           5       1.00      1.00      1.00        10
           6       1.00      1.00      1.00         2

    accuracy                           0.99        73
   macro avg       0.99      0.99      0.99        73
weighted avg       0.99      0.99      0.99        73

Accuracy:0.99


In [45]:
print('misclassified samples:%d'%(y_test!=y_pred).sum())

misclassified samples:1


In [46]:
dataset.corr()

0.370701   
koebner_phenomenon                                                       0.375926   
polygonal_papules                                                        0.911572   
follicular_papules                                                      -0.140404   
oral_mucosal_involvement                                                 0.887487   
knee and elbow involvement                                              -0.281784   
scalp_involvement                                                       -0.253429   
family_history                                                          -0.156067   
melanin_incontinence                                                     0.941623   
eosinophils_in_the_infiltrate                                            0.039496   
PNL_infiltrate                                                          -0.318750   
fibrosis_of_the_papillary_dermis                                        -0.169175   
exocytosis                                                               0.383551   
acanthosis                                                               0.130193   
hyperkeratosis                                                          -0.164269   
parakeratosis                                                           -0.034364   
clubbing_of_the_rete_ridges                                             -0.296671   
elongation_of_the_rete_ridges                                           -0.405635   
thinning_of_the_suprapapillary_epidermis                                -0.291752   
spongiform_pustule                                                      -0.211549   
munro_microabcess                                                       -0.222404   
focal_hypergranulosis                                                    0.909596   
disappearance_of_the_granular_layer                                     -0.145341   
vacuolisation_and_damage_of_basal_layer                                  1.000000   
spongiosis                                                               0.055340   
saw-tooth_appearance_of_retes                                            0.938359   
follicular_horn_plug                                                    -0.091675   
perifollicular_parakeratosis                                            -0.112860   
inflammatory_monoluclear_inflitrate                                      0.253318   
band-like_infiltrate                                                     0.937521   
Age                                                                      0.129198   
Disease                                                                  0.054779   

                                          spongiosis  \
erythema                                    0.023084   
scaling                                     0.010748   
definite_borders                           -0.249164   
itching                                     0.010451   
koebner_phenomenon                         -0.002478   
polygonal_papules                           0.082789   
follicular_papules                         -0.012057   
oral_mucosal_involvement                    0.123183   
knee and elbow involvement                 -0.417120   
scalp_involvement                          -0.419951   
family_history                             -0.151192   
melanin_incontinence                        0.060781   
eosinophils_in_the_infiltrate               0.157650   
PNL_infiltrate                             -0.124273   
fibrosis_of_the_papillary_dermis           -0.181568   
exocytosis                                  0.568202   
acanthosis                                 -0.071201   
hyperkeratosis                             -0.250894   
parakeratosis                              -0.224684   
clubbing_of_the_rete_ridges                -0.505705   
elongation_of_the_rete_ridges              -0.583316   
thinning_of_the_suprapapillary_epidermis   -0.508326   
spongiform_pustule                         -0.284701   
munro_mi

In [47]:
dataset.to_csv('dermatology3.csv', index=False)

In [49]:


# loading model from disk to compare results




0.136986301369863